services:
  db:
    container_name: order_service_pg
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  cache:
    container_name: order_service_redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  